configured_endpoints: 96
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/blaxel%2Fblaxel-abecc5fd9e8904cf06fa73fc091ef6b23101486d3ce6bfcee570bad02bcc4ab1.yml
openapi_spec_hash: f4cf173ada2a24d81ce5353c2eea6ef4
config_hash: 5c6e4e90f246bbfcb88c0cd46432a4d7
