// File manually maintained - not generated by Stainless

package blaxel

import (
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// Config represents the structure of ~/.blaxel/config.yaml
type Config struct {
	Context    ContextConfig     `yaml:"context"`
	Workspaces []WorkspaceConfig `yaml:"workspaces"`
}

// WorkspaceConfig represents a workspace configuration
type WorkspaceConfig struct {
	Name        string      `yaml:"name"`
	Credentials Credentials `yaml:"credentials"`
	Env         string      `yaml:"env"`
}

// ContextConfig represents the current context
type ContextConfig struct {
	Workspace string `yaml:"workspace"`
}

// Credentials represents authentication credentials
type Credentials struct {
	APIKey            string `yaml:"apiKey"`
	AccessToken       string `yaml:"access_token"`
	RefreshToken      string `yaml:"refresh_token"`
	ExpiresIn         int    `yaml:"expires_in"`
	DeviceCode        string `yaml:"device_code"`
	ClientCredentials string `yaml:"client_credentials"`
}

// IsValid returns true if any credential is set
func (c Credentials) IsValid() bool {
	return c.APIKey != "" || c.AccessToken != "" || c.RefreshToken != "" || c.ClientCredentials != ""
}

// LoadConfig loads the configuration from ~/.blaxel/config.yaml
func LoadConfig() (Config, error) {
	config := Config{}
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return config, err
	}

	configPath := filepath.Join(homeDir, ".blaxel", "config.yaml")
	data, err := os.ReadFile(configPath)
	if err != nil {
		// If file doesn't exist, return empty config (not an error)
		if os.IsNotExist(err) {
			return config, nil
		}
		return config, err
	}

	if err := yaml.Unmarshal(data, &config); err != nil {
		// Invalid YAML, return empty config
		return Config{}, nil
	}

	return config, nil
}

// LoadCredentials loads credentials for a specific workspace
func LoadCredentials(workspaceName string) (Credentials, error) {
	config, err := LoadConfig()
	if err != nil {
		return Credentials{}, err
	}

	for _, workspace := range config.Workspaces {
		if workspace.Name == workspaceName {
			return workspace.Credentials, nil
		}
	}

	return Credentials{}, nil
}

// CurrentContext returns the current workspace context
func CurrentContext() (ContextConfig, error) {
	config, err := LoadConfig()
	if err != nil {
		return ContextConfig{}, err
	}
	return config.Context, nil
}
