// File manually maintained - not generated by Stainless

package blaxel

import (
	"fmt"
	"os"
	"sync"
)

// Environment represents the deployment environment
type Environment string

const (
	EnvProduction  Environment = "prod"
	EnvDevelopment Environment = "dev"
	EnvLocal       Environment = "local"
)

// EnvironmentConfig holds all URL configurations for an environment
type EnvironmentConfig struct {
	BaseURL     string
	AppURL      string
	RunURL      string
	RegistryURL string
}

// environments maps environment names to their configurations
var environments = map[Environment]EnvironmentConfig{
	EnvProduction: {
		BaseURL:     "https://api.blaxel.ai/v0",
		AppURL:      "https://app.blaxel.ai",
		RunURL:      "https://run.blaxel.ai",
		RegistryURL: "https://us.registry.blaxel.ai",
	},
	EnvDevelopment: {
		BaseURL:     "https://api.blaxel.dev/v0",
		AppURL:      "https://app.blaxel.dev",
		RunURL:      "https://run.blaxel.dev",
		RegistryURL: "https://eu.registry.blaxel.dev",
	},
	EnvLocal: {
		BaseURL:     "http://localhost:8080/v0",
		AppURL:      "http://localhost:3000",
		RunURL:      "https://run.blaxel.dev",
		RegistryURL: "https://eu.registry.blaxel.dev",
	},
}

// Global environment state
var (
	currentEnv    Environment = EnvProduction
	currentConfig EnvironmentConfig
	envMutex      sync.RWMutex
)

func init() {
	currentConfig = environments[EnvProduction]
}

// SetEnvironment switches to a predefined environment
func SetEnvironment(env Environment) {
	envMutex.Lock()
	defer envMutex.Unlock()
	if config, ok := environments[env]; ok {
		currentEnv = env
		currentConfig = config
	}
}

// GetEnvironment returns the current environment
func GetEnvironment() Environment {
	envMutex.RLock()
	defer envMutex.RUnlock()
	return currentEnv
}

// GetEnvironmentConfig returns the current environment configuration
func GetEnvironmentConfig() EnvironmentConfig {
	envMutex.RLock()
	defer envMutex.RUnlock()
	return currentConfig
}

// URL getters

// GetBaseURL returns the API base URL for the current environment
func GetBaseURL() string {
	envMutex.RLock()
	defer envMutex.RUnlock()
	return currentConfig.BaseURL
}

// GetAppURL returns the web app URL for the current environment
func GetAppURL() string {
	envMutex.RLock()
	defer envMutex.RUnlock()
	return currentConfig.AppURL
}

// GetRunURL returns the runtime/execution URL for the current environment
func GetRunURL() string {
	envMutex.RLock()
	defer envMutex.RUnlock()
	return currentConfig.RunURL
}

// GetRegistryURL returns the container registry URL for the current environment
func GetRegistryURL() string {
	envMutex.RLock()
	defer envMutex.RUnlock()
	return currentConfig.RegistryURL
}

// Custom URL setters (for env var overrides)

// SetBaseURL overrides the API base URL
func SetBaseURL(url string) {
	envMutex.Lock()
	defer envMutex.Unlock()
	currentConfig.BaseURL = url
}

// SetAppURL overrides the web app URL
func SetAppURL(url string) {
	envMutex.Lock()
	defer envMutex.Unlock()
	currentConfig.AppURL = url
}

// SetRunURL overrides the runtime/execution URL
func SetRunURL(url string) {
	envMutex.Lock()
	defer envMutex.Unlock()
	currentConfig.RunURL = url
}

// SetRegistryURL overrides the container registry URL
func SetRegistryURL(url string) {
	envMutex.Lock()
	defer envMutex.Unlock()
	currentConfig.RegistryURL = url
}

// LoadEnvironmentFromConfig loads the environment for a workspace from the config file
func LoadEnvironmentFromConfig(workspaceName string) Environment {
	cfg, err := LoadConfig()
	if err != nil {
		return EnvProduction
	}

	for _, ws := range cfg.Workspaces {
		if ws.Name == workspaceName {
			if ws.Env != "" {
				return Environment(ws.Env)
			}
			break
		}
	}

	return EnvProduction
}

// InitializeEnvironment sets up the environment based on workspace and env vars
func InitializeEnvironment(workspaceName string) {
	// Check BL_ENV first - it takes precedence over config file
	var env Environment
	if envStr := os.Getenv("BL_ENV"); envStr != "" {
		env = Environment(envStr)
	} else {
		// Fall back to workspace config
		env = LoadEnvironmentFromConfig(workspaceName)
	}
	SetEnvironment(env)

	// Then, apply env var overrides for individual URLs
	ApplyEnvironmentOverrides()
}

// ApplyEnvironmentOverrides applies environment variable overrides
func ApplyEnvironmentOverrides() {
	if url := os.Getenv("BL_API_URL"); url != "" {
		SetBaseURL(url)
	}
	if url := os.Getenv("BL_RUN_URL"); url != "" {
		SetRunURL(url)
	}
	if url := os.Getenv("BL_APP_URL"); url != "" {
		SetAppURL(url)
	}
}

// URL builder helpers

// BuildSandboxURL constructs the sandbox URL for a given workspace and sandbox name
func BuildSandboxURL(workspace, sandboxName string) string {
	return fmt.Sprintf("%s/%s/sandboxes/%s", GetRunURL(), workspace, sandboxName)
}

// BuildResourceURL constructs a resource URL for the run endpoint
func BuildResourceURL(workspace, resourceType, resourceName string) string {
	return fmt.Sprintf("%s/%s/%s/%s", GetRunURL(), workspace, resourceType, resourceName)
}

// BuildOAuthDeviceURL returns the device login URL
func BuildOAuthDeviceURL() string {
	return GetBaseURL() + "/login/device"
}

// BuildOAuthTokenURL returns the OAuth token URL
func BuildOAuthTokenURL() string {
	return GetBaseURL() + "/oauth/token"
}

// BuildObservabilityLogsURL returns the logs endpoint URL
func BuildObservabilityLogsURL() string {
	return GetBaseURL() + "/observability/logs"
}
