// File manually maintained - not generated by Stainless.
package blaxel

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"io"
	mathrand "math/rand/v2"
	"net"
	"net/http"
	"time"

	"github.com/blaxel-ai/sdk-go/option"
)

// ProcessError means an operation could not determine the command's outcome.
// It does not mean the command failed or stopped. Use Identifier with Get, Wait,
// or GetLogs to recover the original command; do not submit the command again.
// LastKnownProcess is an observation, not a guarantee of the current state.
// Unwrap preserves errors.Is/errors.As support for the underlying cause.
type ProcessError struct {
	Operation        string
	Identifier       string
	LastKnownProcess *ProcessResponse
	Cause            error
}

func (e *ProcessError) Error() string {
	return fmt.Sprintf("process %q: could not %s; command outcome is unconfirmed: %v", e.Identifier, e.Operation, e.Cause)
}
func (e *ProcessError) Unwrap() error { return e.Cause }

func prepareProcessRequest(body ProcessRequestParam) ProcessRequestParam {
	if body.Name.Or("") == "" {
		body.Name = String("proc-" + rand.Text())
	}
	return body
}

func terminalProcessStatus(status ProcessResponseStatus) bool {
	switch status {
	case ProcessResponseStatusCompleted, ProcessResponseStatusFailed, ProcessResponseStatusKilled, ProcessResponseStatusStopped:
		return true
	default:
		return false
	}
}

func retryableProcessObservation(err error) bool {
	var apiErr *Error
	if errors.As(err, &apiErr) {
		switch apiErr.StatusCode {
		case http.StatusRequestTimeout, http.StatusTooManyRequests, http.StatusInternalServerError, http.StatusBadGateway, http.StatusServiceUnavailable, http.StatusGatewayTimeout:
			return true
		default:
			return false
		}
	}
	var networkError net.Error
	return errors.As(err, &networkError) || errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) || errors.Is(err, context.DeadlineExceeded)
}

func processWaitDuration(maxWait time.Duration) time.Duration {
	if maxWait == 0 {
		return time.Minute
	}
	return maxWait
}

func (r *SandboxInstanceProcessService) waitForProcess(ctx context.Context, identifier string, maxWait, interval time.Duration) (*ProcessResponse, error) {
	var last *ProcessResponse
	failure := func(cause error) (*ProcessResponse, error) {
		return nil, &ProcessError{Operation: "wait for completion", Identifier: identifier, LastKnownProcess: last, Cause: cause}
	}
	maxWait = processWaitDuration(maxWait)
	if maxWait < 0 || interval < 0 {
		return failure(fmt.Errorf("maxWait and interval must not be negative"))
	}
	if interval == 0 {
		interval = time.Second
	}
	ctx, cancel := context.WithTimeout(ctx, maxWait)
	defer cancel()
	delay := interval
	var lastFailure error
	for {
		if err := ctx.Err(); err != nil {
			return failure(errors.Join(err, lastFailure))
		}
		// The loop owns retries so every attempt and delay shares one deadline.
		process, err := r.Get(ctx, identifier, option.WithMaxRetries(0))
		if err == nil && process != nil {
			last = process
		}
		if ctx.Err() != nil {
			return failure(errors.Join(ctx.Err(), err, lastFailure))
		}
		if err == nil {
			if process == nil {
				return failure(fmt.Errorf("empty process response"))
			}
			if terminalProcessStatus(process.Status) {
				return process, nil
			}
			if process.Status != ProcessResponseStatusRunning {
				return failure(fmt.Errorf("unrecognized process status %q", process.Status))
			}
			lastFailure = nil
			delay = interval
		} else {
			if !retryableProcessObservation(err) {
				return failure(err)
			}
			lastFailure = err
		}
		wait := delay
		if err != nil {
			delay = min(delay, 5*time.Second)
			// Equal jitter avoids synchronized retries across many waiting agents.
			wait = max(time.Nanosecond, time.Duration(float64(delay)*(0.5+mathrand.Float64()/2)))
		}
		timer := time.NewTimer(wait)
		select {
		case <-ctx.Done():
			timer.Stop()
			return failure(errors.Join(ctx.Err(), lastFailure))
		case <-timer.C:
		}
		if err != nil && delay < 5*time.Second {
			delay = min(delay*2, 5*time.Second)
		}
	}
}

// KillAndWait requests a forceful stop and waits until the API reports a terminal
// state. This confirms the API state, not OS-level reaping of the process.
// Canceling ctx stops this operation; canceling Wait alone never stops a command.
func (r *SandboxInstanceProcessService) KillAndWait(ctx context.Context, identifier string, maxWait, interval time.Duration) (*ProcessResponse, error) {
	return r.stopAndWait(ctx, identifier, maxWait, interval, true)
}

// StopAndWait requests a graceful stop and waits until the API reports a terminal
// state. This confirms the API state, not OS-level reaping of the process.
func (r *SandboxInstanceProcessService) StopAndWait(ctx context.Context, identifier string, maxWait, interval time.Duration) (*ProcessResponse, error) {
	return r.stopAndWait(ctx, identifier, maxWait, interval, false)
}

func (r *SandboxInstanceProcessService) stopAndWait(ctx context.Context, identifier string, maxWait, interval time.Duration, force bool) (*ProcessResponse, error) {
	maxWait = processWaitDuration(maxWait)
	if maxWait < 0 || interval < 0 {
		return nil, &ProcessError{Operation: "stop and confirm completion", Identifier: identifier, Cause: fmt.Errorf("maxWait and interval must not be negative")}
	}
	ctx, cancel := context.WithTimeout(ctx, maxWait)
	defer cancel()
	var err error
	if force {
		_, err = r.Kill(ctx, identifier, option.WithMaxRetries(0))
	} else {
		_, err = r.Stop(ctx, identifier, option.WithMaxRetries(0))
	}
	if err != nil && !retryableProcessObservation(err) {
		return nil, &ProcessError{Operation: "stop and confirm completion", Identifier: identifier, Cause: err}
	}
	// A lost stop response may follow an accepted signal. Observe its outcome
	// without sending the signal again.
	result, waitErr := r.waitForProcess(ctx, identifier, maxWait, interval)
	if waitErr != nil && err != nil {
		return nil, errors.Join(waitErr, err)
	}
	return result, waitErr
}

var errProcessStreamClosed = errors.New("process log stream explicitly closed")

// Err returns the observed stream failure, if any. Call Wait first to obtain the
// final error. Explicit Close is not a failure. A nil error indicates only that
// streaming ended cleanly, not that the remote command completed.
func (sc *StreamControl) Err() error {
	sc.errMu.Lock()
	defer sc.errMu.Unlock()
	return sc.err
}

func (sc *StreamControl) setError(err error) bool {
	sc.errMu.Lock()
	defer sc.errMu.Unlock()
	if sc.err != nil {
		return false
	}
	sc.err = err
	return true
}
