// File manually maintained - not generated by Stainless

package blaxel

import (
	"context"
	"net/http"
	"strings"

	"github.com/stainless-sdks/blaxel-go/option"
)

// ResourceType represents a resource type with singular and plural forms
type ResourceType struct {
	Singular string
	Plural   string
}

// resourceTypes defines the known resource types for pluralization
var resourceTypes = []ResourceType{
	{Singular: "agent", Plural: "agents"},
	{Singular: "function", Plural: "functions"},
	{Singular: "job", Plural: "jobs"},
	{Singular: "model", Plural: "models"},
	{Singular: "mcp", Plural: "mcps"},
	{Singular: "sandbox", Plural: "sandboxes"},
}

// Run makes an HTTP request to the run endpoint for a resource.
// It uses the existing client infrastructure with the run base URL,
// handling all authentication (API key, access token with refresh, client credentials).
func (r *Client) Run(
	ctx context.Context,
	workspace string,
	resourceType string,
	resourceName string,
	method string,
	path string,
	body any,
	opts ...option.RequestOption,
) (res *http.Response, err error) {
	baseURL := GetRunURL() + "/" + workspace + "/" + pluralizeResourceType(resourceType) + "/" + resourceName
	opts = append(opts, option.WithBaseURL(baseURL))
	opts = append(opts, option.WithResponseBodyInto(&res))
	// Set workspace for token refresh save callback
	if workspace != "" {
		opts = append(opts, option.WithWorkspace(workspace))
	}
	err = r.Execute(ctx, method, path, body, nil, opts...)
	return
}

// RunLocal makes an HTTP request to a local run endpoint (localhost:1338).
// Useful for local development and testing.
func (r *Client) RunLocal(
	ctx context.Context,
	method string,
	path string,
	body any,
	opts ...option.RequestOption,
) (res *http.Response, err error) {
	opts = append(opts, option.WithBaseURL("http://localhost:1338"))
	opts = append(opts, option.WithResponseBodyInto(&res))
	err = r.Execute(ctx, method, path, body, nil, opts...)
	return
}

// pluralizeResourceType converts a singular resource type to its plural form
func pluralizeResourceType(resourceType string) string {
	rt := strings.ToLower(resourceType)
	for _, res := range resourceTypes {
		if strings.ToLower(res.Singular) == rt {
			return res.Plural
		}
	}
	// Default pluralization
	if strings.HasSuffix(rt, "y") {
		return rt[:len(rt)-1] + "ies"
	}
	if strings.HasSuffix(rt, "s") {
		return rt
	}
	return rt + "s"
}
