// File manually maintained - not generated by Stainless

package blaxel

import (
	"context"
	"net/http"
	"slices"

	"github.com/blaxel-ai/sdk-go/internal/requestconfig"
	"github.com/blaxel-ai/sdk-go/option"
	"github.com/blaxel-ai/sdk-go/packages/param"
)

// SandboxSystemService contains methods for sandbox system operations including
// upgrade and health check functionality.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewSandboxSystemService] method instead.
type SandboxSystemService struct {
	Options []option.RequestOption
}

// NewSandboxSystemService generates a new service that applies the given options
// to each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewSandboxSystemService(opts ...option.RequestOption) (r SandboxSystemService) {
	r = SandboxSystemService{}
	r.Options = opts
	return
}

// Upgrade triggers an upgrade of the sandbox-api process. Returns immediately
// before upgrading. The upgrade will: download the specified binary from GitHub
// releases, validate it, and restart. All running processes will be preserved
// across the upgrade.
func (r *SandboxSystemService) Upgrade(ctx context.Context, body SandboxSystemUpgradeParams, opts ...option.RequestOption) (res *UpgradeTriggerResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "upgrade"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Health returns health status and system information including upgrade count
// and binary details. Also includes last upgrade attempt status with detailed
// error information if available.
func (r *SandboxSystemService) Health(ctx context.Context, opts ...option.RequestOption) (res *HealthResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "health"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

// SandboxSystemUpgradeParams contains parameters for upgrading the sandbox-api.
type SandboxSystemUpgradeParams struct {
	// Base URL for releases (useful for forks)
	BaseURL param.Opt[string] `json:"baseUrl,omitzero"`
	// Version to upgrade to: "develop", "main", "latest", or specific tag like "v1.0.0"
	Version param.Opt[string] `json:"version,omitzero"`
	paramObj
}

func (r SandboxSystemUpgradeParams) MarshalJSON() (data []byte, err error) {
	type shadow SandboxSystemUpgradeParams
	return param.MarshalObject(r, (*shadow)(&r))
}

// HealthResponse contains health status and system information
type HealthResponse = HealthCheckResponse
