// File manually maintained - not generated by Stainless

package blaxel

import (
	"context"
	"slices"

	"github.com/stainless-sdks/blaxel-go/option"
)

// NewInstance creates a new sandbox and returns a SandboxInstance with scoped services.
// This allows fluent access to sub-resources like previews:
//
//	sbx, err := client.Sandboxes.NewInstance(ctx, params)
//	preview, err := sbx.Previews.New(ctx, previewParams)
//	token, err := preview.Tokens.New(ctx, tokenParams)
func (r *SandboxService) NewInstance(ctx context.Context, body SandboxNewParams, opts ...option.RequestOption) (*SandboxInstance, error) {
	opts = slices.Concat(r.Options, opts)
	sandbox, err := r.New(ctx, body, opts...)
	if err != nil {
		return nil, err
	}
	return newSandboxInstance(sandbox, opts), nil
}

// GetInstance returns a sandbox as a SandboxInstance with scoped services.
// This allows fluent access to sub-resources like previews:
//
//	sbx, err := client.Sandboxes.GetInstance(ctx, "my-sandbox")
//	preview, err := sbx.Previews.New(ctx, previewParams)
//	token, err := preview.Tokens.New(ctx, tokenParams)
func (r *SandboxService) GetInstance(ctx context.Context, sandboxName string, opts ...option.RequestOption) (*SandboxInstance, error) {
	opts = slices.Concat(r.Options, opts)
	sandbox, err := r.Get(ctx, sandboxName, SandboxGetParams{}, opts...)
	if err != nil {
		return nil, err
	}
	return newSandboxInstance(sandbox, opts), nil
}

// UpdateInstance updates a sandbox's configuration and returns a SandboxInstance with scoped services.
func (r *SandboxService) UpdateInstance(ctx context.Context, sandboxName string, body SandboxUpdateParams, opts ...option.RequestOption) (*SandboxInstance, error) {
	opts = slices.Concat(r.Options, opts)
	sandbox, err := r.Update(ctx, sandboxName, body, opts...)
	if err != nil {
		return nil, err
	}
	return newSandboxInstance(sandbox, opts), nil
}

// DeleteInstance permanently deletes a sandbox and returns a SandboxInstance.
// This action cannot be undone.
func (r *SandboxService) DeleteInstance(ctx context.Context, sandboxName string, opts ...option.RequestOption) (*SandboxInstance, error) {
	opts = slices.Concat(r.Options, opts)
	sandbox, err := r.Delete(ctx, sandboxName, opts...)
	if err != nil {
		return nil, err
	}
	return newSandboxInstance(sandbox, opts), nil
}

// SandboxInstance wraps a Sandbox with scoped services that automatically use
// the sandbox name in API calls.
type SandboxInstance struct {
	*Sandbox
	// Previews provides preview operations scoped to this sandbox
	Previews *SandboxInstancePreviewService
}

// SandboxInstancePreviewService provides preview operations for a specific sandbox
type SandboxInstancePreviewService struct {
	sandboxName string
	options     []option.RequestOption
	service     *SandboxPreviewService
}

// New creates a preview for this sandbox and returns a PreviewInstance with scoped token service
func (r *SandboxInstancePreviewService) New(ctx context.Context, body SandboxPreviewNewParams, opts ...option.RequestOption) (*PreviewInstance, error) {
	preview, err := r.service.New(ctx, r.sandboxName, body, opts...)
	if err != nil {
		return nil, err
	}
	return newPreviewInstance(preview, r.sandboxName, r.options), nil
}

// Get returns a preview by name for this sandbox as a PreviewInstance
func (r *SandboxInstancePreviewService) Get(ctx context.Context, previewName string, opts ...option.RequestOption) (*PreviewInstance, error) {
	preview, err := r.service.Get(ctx, previewName, SandboxPreviewGetParams{SandboxName: r.sandboxName}, opts...)
	if err != nil {
		return nil, err
	}
	return newPreviewInstance(preview, r.sandboxName, r.options), nil
}

// Update updates a preview for this sandbox and returns a PreviewInstance
func (r *SandboxInstancePreviewService) Update(ctx context.Context, previewName string, params SandboxInstancePreviewUpdateParams, opts ...option.RequestOption) (*PreviewInstance, error) {
	preview, err := r.service.Update(ctx, previewName, SandboxPreviewUpdateParams{
		SandboxName: r.sandboxName,
		Preview:     params.Preview,
	}, opts...)
	if err != nil {
		return nil, err
	}
	return newPreviewInstance(preview, r.sandboxName, r.options), nil
}

// List returns all previews for this sandbox
func (r *SandboxInstancePreviewService) List(ctx context.Context, opts ...option.RequestOption) (*[]Preview, error) {
	return r.service.List(ctx, r.sandboxName, opts...)
}

// Delete deletes a preview for this sandbox
func (r *SandboxInstancePreviewService) Delete(ctx context.Context, previewName string, opts ...option.RequestOption) (*Preview, error) {
	return r.service.Delete(ctx, previewName, SandboxPreviewDeleteParams{SandboxName: r.sandboxName}, opts...)
}

// SandboxInstancePreviewUpdateParams is used for updating previews via SandboxInstance
type SandboxInstancePreviewUpdateParams struct {
	Preview PreviewParam
	paramObj
}

// PreviewInstance wraps a Preview with scoped token service that automatically uses
// the sandbox name and preview name in API calls.
type PreviewInstance struct {
	*Preview
	// Tokens provides token operations scoped to this preview
	Tokens *PreviewInstanceTokenService
}

// PreviewInstanceTokenService provides token operations for a specific preview
type PreviewInstanceTokenService struct {
	sandboxName string
	previewName string
	options     []option.RequestOption
	service     *SandboxPreviewTokenService
}

// New creates a token for this preview
func (r *PreviewInstanceTokenService) New(ctx context.Context, body PreviewTokenParam, opts ...option.RequestOption) (*PreviewToken, error) {
	return r.service.New(ctx, r.previewName, SandboxPreviewTokenNewParams{
		SandboxName:  r.sandboxName,
		PreviewToken: body,
	}, opts...)
}

// List returns all tokens for this preview
func (r *PreviewInstanceTokenService) List(ctx context.Context, opts ...option.RequestOption) (*[]PreviewToken, error) {
	return r.service.Get(ctx, r.previewName, SandboxPreviewTokenGetParams{SandboxName: r.sandboxName}, opts...)
}

// Delete deletes a token for this preview
func (r *PreviewInstanceTokenService) Delete(ctx context.Context, tokenName string, opts ...option.RequestOption) (*SandboxPreviewTokenDeleteResponse, error) {
	return r.service.Delete(ctx, tokenName, SandboxPreviewTokenDeleteParams{
		SandboxName: r.sandboxName,
		PreviewName: r.previewName,
	}, opts...)
}

// newPreviewInstance creates a PreviewInstance from a Preview response
func newPreviewInstance(preview *Preview, sandboxName string, opts []option.RequestOption) *PreviewInstance {
	previewName := preview.Metadata.Name
	tokenService := NewSandboxPreviewTokenService(opts...)

	return &PreviewInstance{
		Preview: preview,
		Tokens: &PreviewInstanceTokenService{
			sandboxName: sandboxName,
			previewName: previewName,
			options:     opts,
			service:     &tokenService,
		},
	}
}

// newSandboxInstance creates a SandboxInstance from a Sandbox response
func newSandboxInstance(sandbox *Sandbox, opts []option.RequestOption) *SandboxInstance {
	sandboxName := sandbox.Metadata.Name
	previewService := NewSandboxPreviewService(opts...)

	return &SandboxInstance{
		Sandbox: sandbox,
		Previews: &SandboxInstancePreviewService{
			sandboxName: sandboxName,
			options:     opts,
			service:     &previewService,
		},
	}
}
