// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package blaxel

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"github.com/blaxel-ai/sdk-go/internal/apijson"
	"github.com/blaxel-ai/sdk-go/internal/requestconfig"
	"github.com/blaxel-ai/sdk-go/option"
	"github.com/blaxel-ai/sdk-go/packages/respjson"
)

// WorkspaceService contains methods and other services that help with interacting
// with the blaxel API.
//
// Note, unlike clients, this service does not read variables from the environment
// automatically. You should not instantiate this service directly, and instead use
// the [NewWorkspaceService] method instead.
type WorkspaceService struct {
	Options []option.RequestOption
}

// NewWorkspaceService generates a new service that applies the given options to
// each request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewWorkspaceService(opts ...option.RequestOption) (r WorkspaceService) {
	r = WorkspaceService{}
	r.Options = opts
	return
}

// Returns detailed information about a workspace including its display name,
// account ID, status, and runtime configuration.
func (r *WorkspaceService) Get(ctx context.Context, workspaceName string, opts ...option.RequestOption) (res *Workspace, err error) {
	opts = slices.Concat(r.Options, opts)
	if workspaceName == "" {
		err = errors.New("missing required workspaceName parameter")
		return
	}
	path := fmt.Sprintf("workspaces/%s", workspaceName)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

// Returns all workspaces the authenticated user has access to. Each workspace is a
// separate tenant with its own resources, team members, and billing.
func (r *WorkspaceService) List(ctx context.Context, opts ...option.RequestOption) (res *[]Workspace, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "workspaces"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type Workspace struct {
	// Autogenerated unique workspace id
	ID string `json:"id"`
	// Workspace account id
	AccountID string `json:"accountId"`
	// The date and time when the resource was created
	CreatedAt string `json:"createdAt"`
	// The user or service account who created the resource
	CreatedBy string `json:"createdBy"`
	// Workspace display name
	DisplayName string `json:"displayName"`
	// Key-value pairs for organizing and filtering resources. Labels can be used to
	// categorize resources by environment, project, team, or any custom taxonomy.
	Labels map[string]string `json:"labels"`
	// Workspace name
	Name string `json:"name"`
	// Workspace write region
	Region string `json:"region"`
	// Runtime configuration for the workspace infrastructure
	Runtime WorkspaceRuntime `json:"runtime"`
	// Workspace status (created, account_binded, account_configured,
	// workspace_configured, ready, error)
	//
	// Any of "created", "account_binded", "account_configured",
	// "workspace_configured", "ready", "error".
	Status WorkspaceStatus `json:"status"`
	// Reason for current status (only set for error status)
	StatusReason string `json:"statusReason"`
	// The date and time when the resource was updated
	UpdatedAt string `json:"updatedAt"`
	// The user or service account who updated the resource
	UpdatedBy string `json:"updatedBy"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ID           respjson.Field
		AccountID    respjson.Field
		CreatedAt    respjson.Field
		CreatedBy    respjson.Field
		DisplayName  respjson.Field
		Labels       respjson.Field
		Name         respjson.Field
		Region       respjson.Field
		Runtime      respjson.Field
		Status       respjson.Field
		StatusReason respjson.Field
		UpdatedAt    respjson.Field
		UpdatedBy    respjson.Field
		ExtraFields  map[string]respjson.Field
		raw          string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r Workspace) RawJSON() string { return r.JSON.raw }
func (r *Workspace) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Workspace status (created, account_binded, account_configured,
// workspace_configured, ready, error)
type WorkspaceStatus string

const (
	WorkspaceStatusCreated             WorkspaceStatus = "created"
	WorkspaceStatusAccountBinded       WorkspaceStatus = "account_binded"
	WorkspaceStatusAccountConfigured   WorkspaceStatus = "account_configured"
	WorkspaceStatusWorkspaceConfigured WorkspaceStatus = "workspace_configured"
	WorkspaceStatusReady               WorkspaceStatus = "ready"
	WorkspaceStatusError               WorkspaceStatus = "error"
)

// Runtime configuration for the workspace infrastructure
type WorkspaceRuntime struct {
	// Infrastructure generation version for the workspace (affects available features
	// and deployment behavior)
	Generation string `json:"generation"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Generation  respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r WorkspaceRuntime) RawJSON() string { return r.JSON.raw }
func (r *WorkspaceRuntime) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
