// File manually maintained - not generated by Stainless

package requestconfig

import (
	"encoding/base64"
	"fmt"
	"strings"
)

// ClientCredentials represents decoded client credentials
type ClientCredentials struct {
	ClientID     string
	ClientSecret string
}

// DecodeClientCredentials decodes base64-encoded client credentials
// in the format base64(clientId:clientSecret)
func DecodeClientCredentials(encoded string) (ClientCredentials, error) {
	// Try base64 decoding first
	decoded, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		// If decoding fails, treat it as already decoded
		decoded = []byte(encoded)
	}

	// Split by colon
	parts := strings.SplitN(string(decoded), ":", 2)
	if len(parts) != 2 {
		return ClientCredentials{}, fmt.Errorf("invalid client credentials format, expected 'clientId:clientSecret'")
	}

	return ClientCredentials{
		ClientID:     parts[0],
		ClientSecret: parts[1],
	}, nil
}
